var quotes = [
  '"Kita harus sentiasa bersiap sedia untuk menghadapi apa jua yang akan berlaku, tetapi tidak boleh dipelihara atau bergerak hanya kerana takut." - Tun Dr. Mahathir Mohamad',
  '"Tanpa pendidikan, kita akan hilang apa-apa." - Tunku Abdul Rahman',
  '"Jangan sekali-kali menyerah. Hari yang hilang tidak akan kembali." - Dato\' Sri Najib Razak',
  '"Hidup ini seperti naik sepeda. Untuk menjaga keseimbangan, anda harus tetap bergerak." - Datuk Lee Chong Wei',
  '"Malaysia adalah sebuah negara yang pelbagai kaum, dan kita semua adalah satu keluarga besar." - Tan Sri Michelle Yeoh',
  '"Saya bangga menjadi anak Malaysia. Saya adalah produk Malaysia." - Nicol David',
  '"Jangan biarkan kelemahan diri kita mengekang kemampuan kita untuk berjaya." - Tan Sri Tony Fernandes',
  '"Kita perlu menjadi bangsa yang satu, berusaha bersama untuk kebaikan Malaysia." - Datuk Seri Anwar Ibrahim',
  '"Kebebasan yang sebenar adalah kebebasan untuk menjadi diri sendiri dan menerima orang lain sebagaimana adanya." - Yasmin Ahmad',
  '"Ketulusan hati adalah kunci kepada kejayaan dalam apa jua bidang." - Tan Sri Dr. Zeti Akhtar Aziz',
  '"Malaysia adalah satu negara yang membudayakan kepelbagaian budaya dan ini adalah kekayaan kita." - Tan Sri Dr. Mahathir Mohamad',
  '"Pemuda adalah generasi peneraju masa depan negara ini." - Tunku Abdul Rahman',
  '"Hanya dengan kerjasama yang padu, kita dapat mencapai kemajuan sejagat." - Dato\' Seri Najib Razak',
  '"Kesukaran adalah peluang untuk meningkatkan diri." - Datuk Lee Chong Wei',
  '"Kita harus menjaga dan memelihara persatuan dalam pelbagai kaum dan agama di Malaysia." - Tan Sri Michelle Yeoh',
  '"Ketekunan dan keazaman adalah kunci kepada kejayaan." - Nicol David',
  '"Kepimpinan adalah tentang mengambil tanggungjawab dan membuat keputusan sukar." - Tan Sri Tony Fernandes',
  '"Kita harus menanam semangat untuk berubah demi masa depan yang lebih baik." - Datuk Seri Anwar Ibrahim',
  '"Kekuatan sebenar adalah dalam kesabaran dan kesungguhan." - Yasmin Ahmad',
  '"Sumber terbesar Malaysia adalah rakyatnya yang berbilang kaum dan budayanya yang kaya." - Tan Sri Dr. Zeti Akhtar Aziz',
  '"Kecemerlangan dalam pendidikan adalah kunci kepada kemajuan negara." - Tun Dr. Mahathir Mohamad',
  '"Kita harus memahami perbezaan budaya untuk hidup dalam keharmonian." - Tunku Abdul Rahman',
  '"Kejayaan adalah hasil dari usaha bersungguh-sungguh." - Dato\' Sri Najib Razak',
  '"Jadilah seorang yang gigih dalam mencapai matlamat anda." - Datuk Lee Chong Wei',
  '"Kesetiaan kepada negara adalah tugas kita sebagai warganegara Malaysia." - Tan Sri Michelle Yeoh',
  '"Berusaha dengan tekun adalah kunci kepada kejayaan dalam sukan dan dalam hidup." - Nicol David',
  '"Kepimpinan adalah tentang membantu orang lain mencapai potensi mereka yang terbaik." - Tan Sri Tony Fernandes',
  '"Kita perlu bekerja bersama untuk mencapai kemajuan dan kesejahteraan bersama." - Datuk Seri Anwar Ibrahim',
  '"Sekarang adalah masa yang tepat untuk berbuat baik dan mencapai kebaikan." - Yasmin Ahmad',
  '"Kita adalah bangsa yang kuat dan berkemampuan untuk menghadapi cabaran apa pun." - Tan Sri Dr. Zeti Akhtar Aziz',
  '"Kita perlu memberi peluang pendidikan yang terbaik kepada generasi muda." - Tun Dr. Mahathir Mohamad',
  '"Kerjasama antara kaum adalah asas kepada kemajuan negara." - Tunku Abdul Rahman',
  '"Kesedaran akan tanggungjawab sosial adalah ciri penting dalam masyarakat." - Dato\' Sri Najib Razak',
  '"Kejayaan dalam sukan adalah hasil daripada latihan dan keupayaan untuk mengatasi cabaran." - Datuk Lee Chong Wei',
  '"Kita adalah satu keluarga besar Malaysia, dan kita harus menjaga persatuan ini." - Tan Sri Michelle Yeoh',
  '"Ketekunan dan dedikasi adalah kunci kepada keunggulan dalam sukan." - Nicol David',
  '"Kepimpinan adalah tentang membimbing dan memberi contoh yang baik." - Tan Sri Tony Fernandes',
  '"Kita harus berusaha bersama untuk mencapai cita-cita besar negara kita." - Datuk Seri Anwar Ibrahim',
  '"Ketulusan hati adalah sifat terbaik dalam seseorang." - Yasmin Ahmad',
  '"Kita perlu menghargai kepelbagaian budaya yang menjadi kekuatan negara kita." - Tan Sri Dr. Zeti Akhtar Aziz',
  '"Pendidikan adalah kunci kepada masa depan yang cerah untuk generasi kita." - Tun Dr. Mahathir Mohamad',
  '"Kita adalah satu Malaysia, dan kita harus hidup bersama dalam keharmonian." - Tunku Abdul Rahman',
  '"Kepercayaan diri adalah asas kepada kejayaan dalam apa jua bidang." - Dato\' Sri Najib Razak',
  '"Kejayaan dalam sukan adalah hasil daripada tekun berlatih dan keazaman." - Datuk Lee Chong Wei',
  '"Kita adalah satu bangsa Malaysia yang mesti bersatu dan berusaha bersama." - Tan Sri Michelle Yeoh',
  '"Kerja keras dan semangat tidak pernah mengkhianati." - Nicol David',
  '"Kepimpinan adalah tentang membimbing dan memberi dorongan kepada orang lain." - Tan Sri Tony Fernandes',
  '"Kita perlu berusaha untuk membangunkan negara dan masyarakat kita." - Datuk Seri Anwar Ibrahim',
  '"Kerjasama adalah kunci kepada kemajuan dalam masyarakat kita." - Yasmin Ahmad'
];

function getQuote() {
  var randNum = Math.floor(Math.random() * quotes.length);
  document.getElementById('quote').innerHTML = quotes[randNum];
}
